# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

baseurl: "" # the subpath of your site, e.g. /blog
url: "http://www.brycematthew.net" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock

# other settings
encoding: utf-8

# visit https://github.com/mojombo/jekyll/wiki/Configuration for more settings

paginate: 10 # pagination based on number of posts
paginate_path: "page:num"
exclude: ["README.md"] # files to exclude
highlighter: pygments
markdown: kramdown
disqus: disqus_IxPpPZVlvb
google_analytics: 

defaults:
  -
    scope:
      path: "" # empty string for all files
    values:
      title: Bryce's Blog

description: The personal musings of Solutions Engineer and IT Pro Veteran Bryce McDonald
author:
  name: Bryce McDonald
  email: bryce@northcodesolutions.com
  github: mcdonaldbm
  twitter: _brycemcdonald
  pinterest:
  linkedin: mcdonaldbm
  bio: IT Pro Veteran and Solutions Engineer specializing in Powershell and automations
  email_md5: e2768e2137a7ad8647b9bac511cbeb74

rss_path: feed.xml
categories_path: categories.html
tags_path: tags.html

# set it as url of an image
# sidebar_background_image: https://www.dropbox.com/s/g9h23zrycedxtk5/sky.png?raw=1

BASE_PATH:

gems:
  - jekyll-paginate